### ISSUE TITLE
vitess sql parser can't parse some sql 

### ISSUE THREAD

**Issue by jiyeyuran** [youtube/vitess#1078]
It seems that sql parser got problems when parsing following sqls:
1. INSERT INTO UserTaskProgress (UserId,Progress) VALUES (?,?) ON DUPLICATE KEY UPDATE Progress=1+values(Progress)
2. SELECT * FROM Users JOIN Groups USING(Gid) WHERE Gid>100

The sql parser can't figure out "1+values(Progress)" AND "USING"

**Comment by sougou** [comment]
The high level answer to your question is that we currently don't strive for full backward compatibility with MySQL. However, if there's something you can't achieve with a simple work-around, then we can look at adding support for such a construct.

For #1: We previously never allowed upserts, because they were not safe for statement-based replication. However, I recently made some changes to support simple constructs where vttablet breaks it up into replication-safe statements. But it doesn't support the full syntax. In your particular case, all you have to do is supply the value you already have in hand instead of using the 'values' construct. I know this is inconvenient in the case of multi-row upserts. But we didn't think somebody would need it.

For #2: You should be able to trivially replace USING(Gid) with WHERE Users.Gid = Groups.Gid.
