### ISSUE TITLE
SQL Escaping in sqltypes package and LIKE clauses

### ISSUE THREAD

**Issue by jzelinskie** [youtube/vitess#1083]
The logic around [this line](https://github.com/youtube/vitess/blob/4de82fd04acc67f7edad34856b1b79cf93566340/go/sqltypes/sqltypes.go#L338) doesn't work with the weird rules for escaping a LIKE clause.

For example, if you want to escape a `%` in a LIKE clause such that it means the actual literal `%` and not a wildcard, you're supposed to escape it with `\\%`. When your writer sees these backslashes, it doubles them all creating `\\\\%`.

I bet you guys don't need escaping in your personal LIKE clauses (yet), but I'm trying to build a SQL query composition library which used a vendored fork of this package and I wanted to see if I could upstream some changes to make it still viable.

Would you guys somehow be interested in a fix? I'm not sure exactly what it would look like, right now.

**Comment by sougou** [comment]
I think it's working as intended. If you look at this test case: https://github.com/youtube/vitess/blob/master/data/test/sqlparser_test/parse_pass.sql#L125. The expected output is the original query itself. The reason why it works is because the tokenizer un-escapes the string when it reads it and it gets re-escaped when written.
There is another code path where a string could be supplied as bind variable. In that case, the rules are different. You're supposed to supply the unescaped string. In your case, you have to supply "\%" and vitess will escape it as "\\%". The reason why bind variables follow different rules is because they can contain arbitrary binary data.
I think this covers all use cases, but let me know if there's a situation where it would not.

Additional note: This is why vitess supports only utf-8 or latin-1 encoding. The escaping rules for these encodings can be character-set agnostic.

**Comment by sougou** [comment]
Ironically, github escaped my backslashes in the message :). I've now quoted them.

**Comment by jzelinskie** [comment]
Ah! It looks like the test was simply incorrect. I tested in MySQL and `\\%` is indeed what you want (which because of Go's string escaping is rendered as `\\\\%`.

Thanks a bunch for the explanation. Everything looks good!
