### ISSUE TITLE
examples/kubernetes/env.sh - ExternalIP and Vagrant Kubernetes

### ISSUE THREAD

**Issue by nirving-versent** [youtube/vitess#1114]
According to https://github.com/youtube/vitess/blob/master/examples/kubernetes/env.sh#L14 it uses the expression `ExternalIP`` to help build `VTCTLD_ADDR`. This may not be available due to some containers not being able to expose an ExternalIP. Is it a good idea to fall back to `LegacyHostIP` if `ExternalIP` is not available.

This appears to work for Vagrant instances.

**Comment by alainjobart** [comment]
Thank you for the comment! We'll fix our side early next week (the person working on this is traveling at the moment).

**Comment by enisoc** [comment]
Thanks for the report @nirving-versent. Do you have an example output for `kubectl get -o yaml nodes` to show? I don't have a Vagrant setup handy, and it seems like LegacyHostIP may be Vagrant-specific since it isn't in the official API docs:

```
node address type, one of Hostname, ExternalIP or InternalIP
```
http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_nodeaddress

**Comment by enisoc** [comment]
I was able to get Vagrant working, so I got what I needed. I'll have a fix soon.
