### ISSUE TITLE
PDO Compliance

### ISSUE THREAD

**Issue by joltup** [youtube/vitess#1212]
In the guide you mention that:

"Client libraries should integrate with the following language-specific database drivers, though this support is not yet provided:"

PDO is listed as one of those. Our application currently relies on PDO. 
I would love to get information on the plans or current state of this compatibility. I'm wondering what might be difficult about making the client PDO compliant and if there are any specific plans to implement that on your end.

**Comment by enisoc** [comment]
Our current state is that we have a custom Vitess API that is consistent in all languages (PHP, Java, etc.). We plan to implement language-specific drivers (like PDO) on top of the Vitess API.

The challenge is that because we handle shard routing on behalf of the app, we need to know the sharding key value that each query corresponds to. For example, if the sharding key is user_id, we need the app to tell us which user_id(s) this query is about, so we can route it to the proper shard(s). APIs like PDO weren't designed with the plumbing for us to receive this extra info from the app.

The sharding key requirement is removed in the new V3 API, which is in development. With the V3 API, you can send just the plain query, and Vitess will automatically figure out which sharding key (e.g. which user_id) the query is about. For example, it can look at the WHERE clause or the column values of an INSERT. For more details, you can see the [VTGate V3](http://vitess.io/doc/VTGateV3/) design doc.

So our drivers for PDO/JDBC/etc. will target the V3 API. The V3 API is available now as a preview feature in Vitess 2.0.0 alpha, and we have begun implementing language-specific drivers based on V3 as a proof-of-concept, such as the [Go driver](https://github.com/youtube/vitess/blob/master/go/vt/client/client.go). We'll likely start adding V3 drivers for PHP and other languages after Vitess 2.0.0 hits final release. The V3 API itself will also be polished over the next few months to prepare for its official feature launch in a later Vitess release.

**Comment by sougou** [comment]
I have a working proof-of-concept for V3. You can check out the demo under examples/demo.  It lets you send queries to a sharded cluster and shows the effects on each table. I just checked in a change to make it easy to launch.
We'll be expanding the feature to handle more query constructs, and improving the tooling to make it more usable in the next few months. But the core V3 is functional for anyone who wants to try.

**Comment by joltup** [comment]
@sougou & @ enisoc: That's super good news. We have been working out our sharding plan because some of our tables are getting really big. I came across vitess and got super excited about the features and tooling. While looking into what it would take to use vitess to manage our sharing, I saw the plans for PDO. That would save us a lot of time because our server code is built around PDO. I'm not sure on our timeline but it's good to know that things are moving forward and that the community/project is alive! I'm super excited about vitess. Thanks guys!

**Comment by enisoc** [comment]
@joltup FYI, you can subscribe to our low-volume [announcement mailing list](https://groups.google.com/forum/#!forum/vitess-announce) if you'd like to be notified of major new features and releases.

**Comment by Rastusik** [comment]
Hi all, wasn't there a link to a custom PHP PDO interface implementation for Vitess? I'm almost 100% I saw it here and then it disappeared for some unknown reason

**Comment by enisoc** [comment]
I've never heard of anyone writing a PDO implementation yet.

**Comment by tslater** [comment]
+1

**Comment by joltup** [comment]
@Rastusik I didn't develop one, unfortunately. I would love to know if there was one!

**Comment by tslater** [comment]
Does that mean there's a community version? Anyone know where to find it?

**Comment by michael-berlin** [comment]
@tslater We haven't written the PDO driver yet and we are not aware that somebody externally wrote one. But we want to do it eventually.

If anybody is interested in implementing the Vitess PDO driver (which would use the existing Vitess PHP client), please reach out to us.

**Comment by Rastusik** [comment]
I am currently trying to make a PHP version of the PDO handler for Vitess (not exactly a PDO driver, but a class with the same interface (actually methods) as the core PDO classes. I don't know if you had something like that in mind, but I don't know any other way to implement it using the existing PHP client. Is this what you have in mind? Can this be of any help to you?

I think I also found a bug, the details are mentioned here:
https://groups.google.com/d/msg/vitess/z9-IJAnNPhE/VRROrEL_EQAJ

**Comment by Rastusik** [comment]
@joltup there might be one soon, but only a PHP implementation, don't know if that would be enough for you

**Comment by joltup** [comment]
@Rastusik That's awesome! PHP is great. I'll be watching for it.

**Comment by Rastusik** [comment]
@joltup check out the beta version here: https://github.com/pixelfederation/vitess-php-pdo

**Comment by enisoc** [comment]
We now link to Pixel Federation's PDO adapter from our repo:

https://github.com/youtube/vitess/tree/master/php
