### ISSUE TITLE
server side prepared statement support

### ISSUE THREAD

**Issue by ChinaXing** [youtube/vitess#1264]
does vitess support "server side prepared statement" when have sharing ?

I think It maybe can't supply this feature. or very hard to accomplete it ?

**Comment by sougou** [comment]
Can you tell us why you need prepared statement?
Overall, people have avoided prepared statements because it's tied to the current connection, and you lose it all if the connection is dropped. So, the app has to recreate all those prepared statements when this happens.
Vitess gives you a more sane alternative: queries with bind variables. It allows you to send a query as 'select * from table where id = :id', and separate bind vars as {"id": 1}, and we have tooling that group such queries that let you collect more interesting stats, etc.
Would that work for you?

**Comment by ChinaXing** [comment]
server side prepared statement has following advantage : 
1.  mysql need not to parse the sql, and reduce some query plan re-produce and etc.
2. the data transferred from client to server will be smaller(which just transfer parameters), which make it faster and reduce the network band needed.

I will have a look at the features  you mentioned.

**Comment by sougou** [comment]
For the longer term, we intend to use the new memcached API: https://dev.mysql.com/doc/refman/5.6/en/innodb-memcached.html, which is more efficient than even prepared statements. Vitess will do it transparently wherever applicable without you having to change the application.
