### ISSUE TITLE
failing to parse query with '.' in alias

### ISSUE THREAD

**Issue by wvell** [youtube/vitess#1512]
I am using the sqlparser directly and try to parse the following query:

`SELECT COUNT(*) AS "test.name" FROM test`

which results in the following error: `syntax error at position 25 near 'test'`
It does not accept the '.' in the alias name while mysql seems to have no problems with it.

see: http://pastebin.com/Vi6Znhbb

**Comment by sougou** [comment]
We've tried not to go overboard on these weird use cases, unless there is a legitimate reason why they're needed. I'll see what I can do about this one.

**Comment by wvell** [comment]
ok thanks :+1:

**Comment by sougou** [comment]
I took a look at how we handle names in general. In order to support random characters efficiently, we'll need to back-quote every name at the time of code generation. The other option will be to scan every name and back-quote if special characters were found, which will be even more expensive.

The first option is a usability concern because queries we generate will be harder to recognize. It's also a huge change because all our tests have to be updated.
The second option is an efficiency concern because we have to scan practically everything before generating code. It's double the work.

Is there a specific use case for this? If not, I'd like to close this bug as infeasible.

**Comment by sougou** [comment]
Closing this for now.
