### ISSUE TITLE
Support for point type (or better error message)

### ISSUE THREAD

**Issue by tslater** [youtube/vitess#1516]
I was loading my schema and kept getting a ```Could not map: 255 to a vitess type``` error message. I finally realized that it was the MySQL _Point_ type column on one of my tables. It would be nice to have seen a better error message of which table it was and the column name instead of 255. Support for the _Point_ column would be even better.

**Comment by sougou** [comment]
Sorry, we currently don't support spatial data types. It's because we haven't spent the time to study them and make sure they'll work from end to end. So, it's something we'll eventually want to support. If this is a blocker, we can look at prioritizing it over other features.
As for the error message, that's something we should be able to fix soon.

**Comment by tslater** [comment]
We only have one column and we're not using it a lot, so don't stress it. The warning would be good though.

**Comment by tslater** [comment]
I also just read this: 

> Vitess supports all MySQL data types, which translate into almost all usual scalar data types. It also provides full SQL support within a shard, including JOIN statements.

On the user guide: http://vitess.io/user-guide/introduction.html.

**Comment by sougou** [comment]
@AndyDiamondstein 
That statement is incorrect. It's likely that the text was written when spatial data types were still not supported by MySQL. Additionally, we also don't support the (almost never used) boolean data type.
