### ISSUE TITLE
Preserve case of column names

### ISSUE THREAD

**Issue by enisoc** [youtube/vitess#1620]
When Vitess receives a query, the tokenizer lowercases all column names so they can be string-compared safely throughout the system. This means all column names returned in the eventual query result are lowercase as well. This causes a problem in PHP when users expect to look up columns by name with the same case they requested in the original query:

``` php
$result = query('select Column from table');
$row = $result->fetch();
echo $row['Column']; // array key doesn't exist
echo $row['column']; // works
```

In Java (JDBC) they address this by specifying that column name lookups are case-insensitive. We recently fixed our Java client to conform to this (https://github.com/youtube/vitess/pull/1572).

We could do something similar in PHP by implementing [ArrayAccess](http://php.net/manual/en/class.arrayaccess.php) or extending [ArrayObject](http://php.net/manual/en/class.arrayobject.php). Each of those has its pros and cons, but either way, the object we return would not be a true array, so things like [array_keys()](http://php.net/manual/en/function.array-keys.php) wouldn't work.

@tslater @Rastusik Can you weigh in on whether this makes sense from a PHP app writer's perspective?

@sougou

**Comment by Rastusik** [comment]
By default PHP uses arrays everywhere, so I think ArrayObject would be a better option, because it would let the older code be compatible. I just hope the implementation would be fast enough, I wouldn't care much about the higher memory footprint, because PHP 7 does a good job with its new architecture and garbage collection.

@enisoc I'm not really sure if there are other pros or cons, if there are any, could you please list them, so maybe we could discuss them if neccessary?

**Comment by enisoc** [comment]
My understanding is that `ArrayAccess` is generally recommended because it's the pure interface that gives the functionality most people are looking for: the ability to use the `[]` operator with their class. `ArrayObject` is a particular implementation of `ArrayAccess` (as well as other interfaces) that is meant to act similar to a built-in `array`. Given that what we want here is something as close as possible to a built-in `array` but with small overrides to lowercase keys before get/set, I agree that `ArrayObject` seems like the right fit.

@Rastusik Do you think it's reasonable that you won't be able to use `array_keys()` and such on the row object, if we switch to returning `ArrayObject` instead of `array`? If that ends up making people change their app code, it might defeat the purpose. Because if they have to change their app code anyway, they may as well change their app code to use lowercase column names in the query and in query result processing, regardless of the case in the actual schema. Then we don't need the performance overhead of `ArrayObject`.

**Comment by Rastusik** [comment]
@enisoc tbh, I haven't seen any code where somebody would call array_keys() on a row from a result set, but I can imagine doing something like this on a framework or library level. But yes, that's a valid point, not sure what's better - but I might incline to the ArrayObject solution anyway, because I would expect less of such code usages in the wild comparing to mixed-case column addressing. 

Is a server solution still not being considered? As another client-side solution, there could be a data transformation after fetching each row, but I think that would slow the whole data manipulation process. This might be a little bit better on the server side, still not perfect though.

**Comment by sougou** [comment]
We're talking about a server solution, but it will take some elaborate effort. So, a short-term solution will need to be worked out until then.

**Comment by tslater** [comment]
@enisoc @Rastusik is right about libraries and frameworks, our framework does seem to call array_keys on the result set in at least a few places. Unfortunately, I think I'm going to run into other problems as well. For example, our rest api sends down json attributes names to clients based off of the attribute names from the query. They expect camel case, so even with this change, we'd have to go through and replace the keys or copy into a new array that has cased keys. It wouldn't solve our problems to be able to call $row[attributeName] instead of $row[attributename], we really just need the attributes to be the proper case. I can't really think of any way to shortcut that on the client without parsing the query and keeping track of the aliases/columns being sent out. I'll keep thinking though.

**Comment by Rastusik** [comment]
@sougou well it's no big deal for PixelFederation, we can wait for the proper server solution. As for the client side solution - one thing just came into my mind. The result rows from Vtgate are being parsed from grpc raw string data anyway. What about including the column-case translation process into the data extraction function? Not quite single responsibility-ish, but ok as a temp fix.

**Comment by enisoc** [comment]
@tslater Thanks that's good feedback. It does sound like a server-side fix is the only elegant way to address that use case. I'll talk to @sougou some more about it.

**Comment by tslater** [comment]
Ok. I wish there was a simpler way.

**Comment by sougou** [comment]
There may be other components, but the rowcache will be the most affected, because it pre-creates the field info based on the schema. So, what it returns will not match the query that came in.
Another incentive for us to deprecate rowcache :).

**Comment by Rastusik** [comment]
Is it Not possible  to also store the column mapping with each query result? Or is it too much work?

**Comment by tslater** [comment]
I'm ok without the row cache.

**Comment by sougou** [comment]
We actually do cache the field info for each query, but we'll need to special case the situation where a query is cache-bound, and no field info has been built for it. If we decide to always send such queries to MySQL, then queries with no bind vars will never benefit from the rowcache.

**Comment by Rastusik** [comment]
I'm also good withoit the row cache, I just think it's a good feature. One of the solutions might be to deprecate it and maybe reintroduce later if needed? A good question also is, how much the cache helps, so a test might come in handy.

@sougou well, I can only ask why there are queries in the cache which don't contain the field info? In my imagination vitess works in a way that every query is being parsed (I've seen AST code for that), so field info should be accessible while caching. Is it not like this? Is it hard to do it?

**Comment by sougou** [comment]
@Rastusik We definitely agree that we have to help the app with caching. We're just trying to figure out how far we want to go in terms of packaging (vs. just providing hooks). It will be demand-driven. So, keep voicing your opinions :).

How much does the cache help: The more point-queries you have, the more it will help. Each point query costs 16K of buffer cache for MySQL. For the rowcache, it will be just the size of the row. It's very dependent on your load pattern.

As for the other case-sensitivity question, Vitess currently relies on MySQL to build field info, which contains names and types. Using the AST, we can only build the names but not the types.
Also, there could be expressions in the select list, in which case it becomes harder to generate the correct name, and even harder to predict the type.
In theory, the AST could be used to predict the name, and we could do some kind of merge with the types obtained from the schema. But it all becomes hairy, and harder to guarantee that we match MySQL's behavior.

**Comment by sougou** [comment]
FTR, the least intrusive solution to keep rowcache working would be to defer usage until field info is built; The first query will always go to MySQL.

**Comment by Rastusik** [comment]
@sougou regarding the packagins vs hooks, for me packaging is a better option, because I don't know which database would be better suited for this use case instead of memcache. If there are other opinions, there still can be hooks with the default (replacable) memcache implementaion of the hooks :)

Regarding the case sensitivity: I don't think you have to predict the column names of the extensions - missing column names from the mapping set would just be fetched from MySQL. The data merge you described might be a little bit hairy, but not so bad as a quick fix for now, if implemented and encapsulated properly.

Regarding the least intrusive solution - that's an acceptable solution too, even better if it's easier to implement :)

**Comment by tslater** [comment]
I think I'm following, but I'm not sure. It seems like there are two issues: typing and case. It sounds like typing is already an issue in the current implementation because of the unpredictability of complex expressions in the where clause. Do I have that right? 

As far as case goes, I'm not super familiar with the innards of clients, but aren't the selected aliases/column names returned by MySQL with the rows? Can you just use the names/cases to build the names or do they, for some other component/reason, need to be known and set before the response is back? Or does the response just not have the column names/proper case for some reason?

**Comment by sougou** [comment]
I might have cried wolf too soon :). It looks like I already do what I said should be done: https://github.com/youtube/vitess/blob/master/go/vt/tabletserver/schema_info.go#L492, which is to fetch the field info upfront.
This is all old code, and I forgot that I had made this change.
In any case, we'll have to chase down all use cases and make sure they're all handled correctly.

**Comment by Rastusik** [comment]
I think vitess somehow transforms the query to lower case so MySQL returns lower cased columns, at least they is the reason why

**Comment by Rastusik** [comment]
sounds promising! :)

**Comment by enisoc** [comment]
To give an update on this: @sougou is working on it now. The plan is to address it within Vitess by matching MySQL's own treatment of case, which is:

* Whatever case is used in the query, use that case in the query result field info.
* Column name lookup remains case-insensitive.

Since this is being addressed on the server side, it's no longer a PHP-specific change, so I'm removing that tag.

**Comment by tslater** [comment]
That sounds awesome. In ```SELECT *``` cases (which there is some support for in Vitess), will the case be the same as the column defined in the table schema?

**Comment by sougou** [comment]
It should, in theory. I'll test it once the feature is done.

**Comment by tslater** [comment]
That's super great news. Thanks for all the hard work!

**Comment by sougou** [comment]
@enisoc: Now that the fix is in, should we revert the case insensitive map change in Java client?

**Comment by enisoc** [comment]
We can't totally revert it, as the JDBC spec still says lookups should be case-insensitive, regardless of the case used in the query. I'll take a look and make sure we don't force lowercase when returning the column names in the Java client.

**Comment by tslater** [comment]
This is awesome. Thanks so much! 
I took a little break from vitess/sharding because of some other immediate needs. 
I'm back on it now, with a little more help...! I'll keep you posted on our progress, but AFAIK we have everything we need to migrate over to vitess. We'll likely be moving to vitess first, and then sharding. We've already pushed to prod some of the tweaks we had to make to be compliant. 
I'm really excited. Thanks for all your hard work!

**Comment by enisoc** [comment]
I checked the Java client, and we shouldn't need to change anything there. The only time we return field info is in `getFields()`:

https://github.com/youtube/vitess/blob/master/java/client/src/main/java/com/youtube/vitess/client/cursor/Row.java#L106

We return the unmodified field info, with whatever case is returned from vtgate:

https://github.com/youtube/vitess/blob/master/java/client/src/main/java/com/youtube/vitess/client/cursor/FieldMap.java#L47
