### ISSUE TITLE
Question on VPS

### ISSUE THREAD

**Issue by hardcoar** [youtube/vitess#1638]
hi im very much interested in using vitess. say i want to deploy vitess on digital ocean for starting (they say its cheaper) and when my app needs to scale, i want i want to transfer the data on my vitess cluster to google container engine. is it possible? if yes, how? (thanks a lot in advance!)

**Comment by enisoc** [comment]
It's definitely possible to move a live Vitess cluster from one provider to another. We did it when we moved from YouTube's datacenters into Google's. There are different trade-offs depending on whether you're willing to take downtime for the switchover.

If you want to do it without downtime, the hard part is actually at the network/security level, not at the Vitess level, because what you need is to bring up the new side and have it replicating live from the old side. As long as the IPs on both sides can connect to each other over some kind of VPN, Vitess doesn't care that you're spanning providers.

If you're ok with downtime, you could bring up an identical set of empty keyspaces on the new side, and then enter downtime, take a backup, copy it to the new side, and restore it there.

**Comment by hardcoar** [comment]
thank you very much for the info.
