### ISSUE TITLE
logging before flag.Parse

### ISSUE THREAD

**Issue by hardcoar** [youtube/vitess#1643]
golang glog is causing this noisy log everytime i make requests to vitess.

it repeats this same error:
`ERROR: logging before flag.Parse: I0416 20:50:46.396633    7517 driver.go:118] Sending queries only to keyspace/shard: test_keyspace/0`

it is caused by this statement:
```
if c.useExecuteShards() {
		log.Infof("Sending queries only to keyspace/shard: %v/%v", c.Keyspace, c.Shard)
	}
```
in driver.go (github.com/youtube/vitess/go/vt/vitessdriver).

any work around on this? is there any way to get rid of this log msg?

**Comment by enisoc** [comment]
The log line is inside the Vitess driver's `Open()` call. Are you trying to open a connection to the database from an `init()` function? Or maybe you didn't call `flag.Parse()` first?

**Comment by enisoc** [comment]
From what I can tell, I think the log line there is ok as long as you don't try to open a DB connection from init(), which we don't recommend. I'll close this for now since I haven't heard back in a while, but feel free to reopen if you still have concerns about this.

**Comment by mattlord** [comment]
Hi @dvaldivia,

If you believe that you're encountering a bug please open a new issue with all of the details here: https://github.com/vitessio/vitess/issues/new?assignees=&labels=Type%3A+Bug%2CNeeds+Triage&template=bug_report.yml&title=Bug+Report%3A+

This bug report is extremely old and the relevant code has drastically changed since then (flag management itself was overhauled in Vitess 15.0). With a test case we can confirm that the issue still exists in main / v17.
