### ISSUE TITLE
GettingStarted.md: can't find dir '/usr/local/opt/mysql56/sbin' after brew install homebrew/versions/mysql56

### ISSUE THREAD

**Issue by geekard** [youtube/vitess#1864]
$ brew install homebrew/versions/mysql56 
$ ls -F  /usr/local/opt/mysql56/
COPYING               README  homebrew.mxcl.mysql56.plist  lib/      my-new.cnf  mysql-test/  scripts/  sql-bench/
INSTALL_RECEIPT.json  bin/    include/   libexec/  my.cnf       share/    support-files/

all binaries are under 'bin' directory.

$ export MYSQL_FLAVOR=MySQL56
$ export VT_MYSQL_ROOT=/usr/local/opt/mysql56
$ ./vttablet-up.sh
Starting MySQL for tablet test-0000000100...
Starting MySQL for tablet test-0000000101...
Starting MySQL for tablet test-0000000102...
Starting MySQL for tablet test-0000000103...
Starting MySQL for tablet test-0000000104...
E0713 13:49:50.487003   22624 mysqlctl.go:229] failed init mysql: /usr/local/opt/mysql56/sbin/mysqld:
E0713 13:49:50.487786   22625 mysqlctl.go:229] failed init mysql: /usr/local/opt/mysql56/sbin/mysqld:
E0713 13:49:50.488194   22623 mysqlctl.go:229] failed init mysql: /usr/local/opt/mysql56/sbin/mysqld:
E0713 13:49:50.488504   22626 mysqlctl.go:229] failed init mysql: /usr/local/opt/mysql56/sbin/mysqld:
E0713 13:49:50.488690   22622 mysqlctl.go:229] failed init mysql: /usr/local/opt/mysql56/sbin/mysqld:

If I soft link 'sbin' to 'bin' :
$ cd /usr/local/opt/mysql56 && ln -sf bin sbin
then tablet start successfully.

**Comment by Rastusik** [comment]
that had to change a couple of months ago, I just realized that I had to create the same symlink as well ... don't know where the sbin part comes from.

**Comment by enisoc** [comment]
@Rastusik What do you think is the best fix? Should we update the docs to recommend adding the symlink?

**Comment by Rastusik** [comment]
@enisoc Yes, I think that should be sufficient. But I still have no idea what the cause of this problem is, it just started a few months ago. I thought that there is a sbin path hardcoded somewhere in the Vitess code. But I haven't searched for it.

Shall I update the docs?

**Comment by enisoc** [comment]
Ah yes, it's hardcoded as sbin in Vitess because that's where it is in Debian/Ubuntu at least. Sorry, I thought you meant that the homebrew package had changed a couple months ago. But you're right that we added the usage of mysqld (previously we only looked for mysqld_safe) at that time: https://github.com/youtube/vitess/commit/fd5cac0879bcb2499c4468062671ccc725ecde12

If you're saying that your package places mysqld in $VT_MYSQL_ROOT/bin rather than sbin, I think I can fix this by looking in both locations.

Thanks for the report, @geekard!
