### ISSUE TITLE
ApplySchema fails due to unhealthy tablets in inactive shards

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#1929]
I was trying to apply some DDLs using ApplySchema command after doing resharding,

The toplogy of my cluster looks as follows:
Active Shards: -80, 80-
Inactive Shards: 0

There was a unhealthy tablet in Shard 0, when i try to execute the DDLS using ApplySchema command, it fails with the following exception:
_W0810 13:32:17.033954   30052 main.go:40] W0810 08:02:17.033040 schema.go:81] Failed to reload schema on slave tablet test-0000000203 in shipment/0 (use vtctl ReloadSchema to try again): rpc error: code = 2 desc = TabletManager.ReloadSchema on test-0000000203 error: WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS() failed: gtid_mode is OFF
W0810 13:32:17.099323   30052 main.go:40] W0810 08:02:17.097957 schema.go:81] Failed to reload schema on slave tablet test-0000000203 in shipment/0 (use vtctl ReloadSchema to try again): rpc error: code = 2 desc = TabletManager.ReloadSchema on test-0000000203 error: WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS() failed: gtid_mode is OFF
W0810 13:32:17.194792   30052 main.go:40] W0810 08:02:17.194464 schema.go:81] Failed to reload schema on slave tablet test-0000000203 in shipment/0 (use vtctl ReloadSchema to try again): rpc error: code = 2 desc = TabletManager.ReloadSchema on test-0000000203 error: WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS() failed: gtid_mode is OFF_

This is due to a tablet in worker state in Shard 0. 
Not sure if its an ideal behavior or not, but shouldn;t the ApplySchema command check for healthy tablets in the Active Shards only?

**Comment by ashudeep-sharma** [comment]
Looks like this line shardNames, err := exec.wr.TopoServer().GetShardNames(ctx, keyspace) in 
**func (exec *TabletExecutor) Open(ctx context.Context, keyspace string) error** function returns all the shards in a keyspace and opens connection to Master Tablet of each shard.

Shouldn;t the _GetShardNames()_ function be modified to return all/active shards for a keyspace?

I see the changes in the following files:
_./go/vt/etcdtopo/shard.go
./go/vt/topo/helpers/tee.go
./go/vt/zktopo/shard.go_
where we need to tweak the _GetShardNames()_ function to return all/active Shards in a keyspace.

**Comment by alainjobart** [comment]
We have an internal bug / feature request to add a flag to shards that are not ready yet to receive schema changes (in the interval after creating shards but before copying the schema when you initiate a resharding operation, for instance). That would take care of the most problematic issue.

What you are seeing is somewhat normal though: after a schema change, tablets are told to reload their schema. Some tablets may be unhealthy and fail that reload. We collect that information and return an error from the whole operation then, but the schema change has been applied, and when the unhealthy tablets re-become healthy they will reload the schema, so there should be no ill effect.

We could change the code to not return an error for tablets that are not otherwise healthy, but we should still try to reload, probably...

**Comment by ashudeep-sharma** [comment]
I was thinking more from the use-case scenario, in the recent change in vtctl UI, it clearly marks the shard as _active_ and _inactive_ as shown in the image.
<img width="711" alt="screen shot 2016-08-10 at 7 30 45 pm" src="https://cloud.githubusercontent.com/assets/12492010/17556515/4fe08f72-5f31-11e6-8b1e-caa8fca1be7e.png">

In one of the scenarios in resharding the Source Shard becomes inactive, i am not sure in what other cases we will have the shard in inactive state. 

Considering the Use-Cases, if at later point of time we need to bring the shard from inactive to active state then we should Apply the Schema on all shards else shouldn;t the operations be applied only on Active Shards in a Keyspace?

**Comment by alainjobart** [comment]
Ah these fit exactly in my first bucket: they are Inactive because they're not serving yet. But they might be fully populated, with filtered replication running, in which case they also need the schema change. The only way to know is if we added the Shard flag that describes if the schema has been copied or not.

**Comment by sougou** [comment]
#2674
