### ISSUE TITLE
Support double quoted alias names

### ISSUE THREAD

**Issue by chrisgillis** [youtube/vitess#1953]
`SELECT field AS "My Field" FROM t1`

Vitess does not appear to support double-quoted alias identifiers. I'm only able to get the above query to work as the following:

`SELECT field as MyField FROM t1`

**Comment by sougou** [comment]
This is a known shortcoming. Supporting this is non-trivial because there are many places where alias names are expected to follow variable naming conventions. For example, we generate bind var names based on alias names. But there may be other such dependencies that we don't know of.

If it's a showstopper, we can prioritize this. Otherwise, I'd wait till some of the more critical features are done.

**Comment by chrisgillis** [comment]
Not a showstopper by any means.
