### ISSUE TITLE
Using extra parenthesis in where clause fails in single shard Select query

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2109]
@sougou 
Currently the following query works:
select * from table where shard_key = xyz limit 10;

but the following query:
select * from table where (shard_key = xyz) limit 10;

fails with the following error:
"unsupported: limits with scatter"

**Comment by sougou** [comment]
The current v3 treats parenthesized expressions as complex. They become blackboxes. So, in the above case, the routing algorithm decides to perform a full scatter.
* If you parenthesized without the limit, the query would have an inefficient plan.
* Since we don't support limit clauses for scatter queries (yet). That query fails.

The issue with parenthesized expressions is that they can lead to arbitrary explosion of complexity, and it may not be possible to map them to a simplified equivalent. However, we can look at handling some trivial cases, or a class of them.

**Comment by ashudeep-sharma** [comment]
We have a use-case in which the application has to perform pagination which is done by using limits, but they are quite sure that it won;t be a scatter query as it uses the shardingKey Column Condition.

The Problem why they are using parenthesis is because hibernate appends parenthesis to the conditions.
Is there a way we can handle it for these kind os use-cases for these type of use-cases in where clause:
All Conditions are separated by AND clauses and one of the condition is (shardingKey = xyz)

**Comment by sougou** [comment]
Looks fairly simple. We should be able to do this here: https://github.com/youtube/vitess/blob/master/go/vt/vtgate/planbuilder/expr.go#L20

**Comment by sougou** [comment]
Closed via #2122
