### ISSUE TITLE
ApplySchema and Backup fails if a dba password is set

### ISSUE THREAD

**Issue by adkhare** [youtube/vitess#2154]
After setting a password for a DBA user, we are seeing that both backups and ApplySchema command fails due to authentication issues:
1. with ApplySchema, it says that the password is used for authentication, but authentication fails
2. with backups, mysqladmin fails to authenticate with mysql and does not use the dba password provided to vttablet.

I had submitted the PR with respect to resolve this issue: https://github.com/youtube/vitess/pull/2148

However, it seems like it has not fixed the issue.

**Comment by michael-berlin** [comment]
Can you prepare some minimal instructions which allow us to reproduce the issue?

For example, you could base it off `examples/local`? (http://vitess.io/getting-started/local-instance.html#start-a-vitess-cluster)

**Comment by adkhare** [comment]
The only change in the examples/local is : 
https://gist.github.com/adkhare/a0785abf8fa3f9891e7111b2e2818b3b

in the new vttablet-up.sh, I have added
   ` -db-config-dba-pass vt_dba_pass \ `
in the construction of `dbconfig_flags` variable

**Comment by pivanof** [comment]
A couple of thoughts:
1) I'd think just adding "-db-config-dba-pass vt_dba_pass" to vttablet-up.sh won't actually change the vt_dba password in the database because the password in the database is defined by init_db.sql. This flag will only change the password used by vttablet when it's trying to connect. And since the password used by vttablet won't match the one in the database, nothing using vt_dba user would work.
2) The PR #2148 is actually not correct. It adds usage of dba password into executeMysqlScript function, but the function is not always called with vt_dba as the user to use. When executing init_db.sql script it's called with 'root' user. And in such case if non-empty dba password is used then authentication would fail.

Amit, can you please fix the problem introduced by your PR and try a different reproduction steps for your problem (something that will actually have non-empty password for vt_dba in the database)?

**Comment by adkhare** [comment]
@pivanof sorry for the confusion.

Yes, init_db.sql is set with the appropriate password in the `grant all on *.* to 'vt_dba'@'localhost' identified by <dba_pass>`.

Even then, its still not being used while applying schema and also backups.

**Comment by pivanof** [comment]
I found a problem. https://github.com/youtube/vitess/pull/2176 would fix it.

**Comment by adkhare** [comment]
Thanks a lot @pivanof.

I think I probably need a code walk through or something like that.

Is there anything that I can go through to have a deep understanding of the code

**Comment by pivanof** [comment]
I'm not sure I understand your last comment and how it's related to this issue. If you are referring to my earlier request to fix the introduced problem, I've fixed it already in #2176.
