### ISSUE TITLE
VerticalSplitDiff doesn't handle table without primary key

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2286]
I get an error like this. It should probably just give a warning and proceed to the rest of the tables. Or maybe VerticalSplitClone should fail in the first place.

> E1122 09:46:04.956612    5204 vtworker.go:81] diff() failed: TableScan(source) failed: Cannot read Fields for query 'SELECT `col1`, `col2` FROM `tab` ORDER BY ': vttablet: rpc error: code = 2 desc = gRPCServerError: error: syntax error at position 81

**Comment by michael-berlin** [comment]
You're right: We should fail if a table does not have a primary key. 

In general, the diff depends on a common sort order for both the source and the destination to correctly compare them.

If you run the clone only once, we don't depend on the sort order. But if you run it again, it tries to reconcile the source and the destination. It does so in the same way as the diff and assumes that the sort order is identical on both sides.

If the table has no PK, but a UNIQUE index, MySQL uses that. But if that's not the case, the sort order would be the insertion order and that might be different on source and destination. See: https://dev.mysql.com/doc/refman/5.7/en/innodb-index-types.html
Since our schema code currently doesn't capture the available indexes, we should play it safe and fail on tables without a PK at clone time.

**Comment by sougou** [comment]
I think this is now addressed. I'll close this unless I hear something back.
