### ISSUE TITLE
Makefile:108: *** "Cannot find protoc binary. Did you execute 'source dev.env'?"

### ISSUE THREAD

**Issue by hadoop835** [youtube/vitess#2302]

**Comment by alainjobart** [comment]
@michael-berlin @pivanof it seems we require protoc to be installed, even if we don't use the Makefile rules to compile the proto. See lines 103 and below in toplevel Makefile.

Could we either make that optional (and only require that for when we build the protos)?

**Comment by alainjobart** [comment]
As a workaround though, installing the protobuf library from https://github.com/google/protobuf will fix this.

**Comment by pivanof** [comment]
Isn't bootstrap and "source dev.env" needed to compile using Makefile anyway?

**Comment by michael-berlin** [comment]
A successful bootstrap.sh invocation will always install gRPC and therefore protobuf including `protoc`.

In this case bootstrap.sh probably partially failed and therefore `protoc` is missing.

A `make build` should succeed without `protoc`. But should it succeed when bootstrap.sh did not succeed? Pavel asked the same question:

> Isn't bootstrap and "source dev.env" needed to compile using Makefile anyway?

At this point I'm leaning towards keeping things simple and requiring bootstrap.sh to succeed.

We could update the error message though and mention bootstrap.sh as well.

@hadoop835 I assume bootstrap.sh failed in your case because of this other issue you posted: https://github.com/youtube/vitess/issues/2303

Please make sure that you successfully executed bootstrap.sh.

**Comment by alainjobart** [comment]
Better error message: https://github.com/youtube/vitess/pull/2314

**Comment by alainjobart** [comment]
Closing this issue then, agreed with Michael.
