### ISSUE TITLE
Build grpc failure in travis environment setup

### ISSUE THREAD

**Issue by wangyipei01** [youtube/vitess#2508]
see the error message in this link:
https://travis-ci.org/youtube/vitess/jobs/195674609

**Comment by michael-berlin** [comment]
I can look at this tomorrow morning.

If anybody gets to it before, be my guest.

In any case, please update this bug with any results to avoid duplicate efforts.

**Comment by alainjobart** [comment]
Maybe it's time we get the pre-packaged gRPC packages, instead of building it ourselves, if available?

**Comment by michael-berlin** [comment]
According to the gRPC Python quickstart: http://www.grpc.io/docs/quickstart/python.html you only need to pip install the "grpcio" package.

We're already doing that and infact that's exactly the step which is currently failing.

I'm wondering why we're still compiling grpc itself. @enisoc do you remember why? You are the last one who changed travis/install_grpc.sh. It might be worth deleting that part? In any case, the manual build is unrelated here.

**Comment by enisoc** [comment]
I'm not 100% sure, but I believe the reason we still compile the C libs is because the PHP extension links against them. The PHP extension itself could be installed with PECL, but that still requires that you have the C libs built and installed already.

If there's a way to install pre-built C libs for gRPC, that would let us stop building it, but I didn't find such an option at the time when I updated us to gRPC 1.0.0.
