### ISSUE TITLE
count(*) return N rows by number of shards

### ISSUE THREAD

**Issue by nizsheanez** [youtube/vitess#2572]
Is it expected behaviour that query:
```
SELECT count(*),id_catalog_config from catalog_config
```
returns 2 rows - one from shard 1 and second from shard 2 (i have 2 shards)
without reduce step

**Comment by sougou** [comment]
First of all, this is an invalid query because it's missing the `group by id_catalog_config`. However, MySQL allows such constructs.

* If `id_catalog_config` did not have a unique vindex, you'll get an `unsupported` error from vitess because it's not capable of performing aggregations after the fact.
* If `id_catalog_config` had a unique vindex, then vitess assumes that it doesn't have to perform post-processing aggregation because the rows from one shard don't mix with the others. However, this would work correctly only if you also specified the `group by`.

In your case, you will get two results, one from each shard. I'm thinking this could be used as a clever work-around for the app to get around the fact that vitess doesn't allow certain aggregate queries to be blindly scattered :). But the application will have to consolidate the multiple rows that were returned.

**Comment by nizsheanez** [comment]
good, thanks
