### ISSUE TITLE
Default Directories in Zookeeper

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2575]
Team, we were trying out the latest build of vitess and while installing we found out that some things have changed. Earlier we have faced the same issue where in it was expected from user to create /zk directory which was fixed in https://github.com/youtube/vitess/pull/1784 .

Now the things have been changed a bit and it expects **/vitess/global** and **/vitess/[cell]**  directory to be created by user.
I think for the user ease shouldn't this be created while starting vtctcl. Any thoughts/suggestions regarding this?

**Comment by michael-berlin** [comment]
Alain is OOO today. He can reply to that tomorrow.

I agree that it would be useful.

**Comment by alainjobart** [comment]
Where I was coming from with this is the production flow we've been using internally (not with ZK but with Chubby):

* create the top-level directory for a topology in the global topo server, with the right permissions / quotas.
* use that directory as the topo_global_root parameter.
* for each cell creation:
  * create the top-level directory for that cell data, with the right permissions / quotas.
  * run 'vtctl AddCellInfo' so the global topo server knows where the cell topo server is.

In this use case, you want the top-level directory creation to be done outside of Vitess, in a way that's controlled by the topo server implementation.

Now I understand in your use case, the topology service is mostly used by Vitess, so de-coupling directory creation and Vitess using the directory has no value, and adds an extra step. I am unsure how to fix it though.

Is vtctld started first in this scenario? We could add a command-line parameter to vtctld so it creates the toplevel topo directory (recursively until the top?) at startup if it doesn't exist. That wouldn't solve each cell topo server info though, we'd still have to specify a server and a root directory (and then maybe create it).

That's where I am, I understand it's a burden to create these directories and specify the servers, I just don't have a better way... What do you all think? Would just recursively creating top-level directories that don't exist be enough? And we'd do it at vtctld startup for the root, and maybe during 'vtctl AddCellInfo' for each cell?

**Comment by harshit-gangal** [comment]
I think these root creation and directory are vitess internals and should/should not be exposed to users. If someone wants to specify them separately then this should be provided as a flag. But otherwise, Vitess should create them on its own. This can be done by any of the service who ever requires that information not precisely vtctl, it can be even created by vttablet or vtgate whichever is started first.

**Comment by bbeaudreault** [comment]
@harshit-gangal the problem here is that vttablet and vtgate don't know the local cell info.  They just know their cell name is `-cell foo`, and have the global cell args.

I think there's no getting around calling `vtctl <global topo args> AddCellInfo -server <local addrs> cell`.  Either that or make it possible to run without a global cell, just the local one.

In terms of cutting down on commands to run, I do agree with @harshit-gangal. Currently we need to run 2-3 commands:  create /vitess/global, create /vitess/local, run AddCellInfo.  I think AddCellInfo could be improved to create all the directories necessary, including global if it is the first cell to be added.

**Comment by alainjobart** [comment]
So the following would work then:

* the first time we open a zk2/etcd2 topo.Server (from anywhere), if the global root directory doesn't exist, we try to create it recursively. Consul doesn't need that, it doesn't create directories.

* when the zk2/etcd2 implementation loads a cell, it will try to open the root directory for that cell. If it doesn't exist, it will try to create it recursively.

This would still require calling AddCellinfo with a server and root for every cell. We could be smart here: if a cell doesn't exist, create the CellInfo with the same server as root, and replace 'global' with 'cell name' in path. I think that's too dangerous.

**Comment by bbeaudreault** [comment]
That sounds good. I think if we have to call AddCellInfo, we might as well pass in the proper server address. I agree with you just assuming could lead to some trouble.

I wonder if it would make sense to default to single cell installation, to help bootstrap new users who may never go to a multi-cell environment. If there were a clear path/command for "upgrading" to a global installation, then it would be a win-win. It might be easier to copy the global topology to an external quorum without downtime rather than move a cell.

**Comment by tirsen** [comment]
Your last suggestion sgtm @alainjobart

**Comment by sougou** [comment]
@alainjobart can this be closed?

**Comment by alainjobart** [comment]
This hasn't been done yet, I'll work on it soon though.

**Comment by alainjobart** [comment]
Added directory auto-creation in the linked PR. I believe this concludes the agreed scope of this issue.
