### ISSUE TITLE
Single shard targeting in V3

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#2634]
There is no way to target a single shard in the V3 APIs.

We need to target single shards for two reasons:

1. We want to shard some of our processing in that we have jobs that process an entire single shard at the time.
2. There's a very large number of scatter/gather functionality that is currently not supported (e.g. limit on joins, order by and so on). Some we can work around on the query level but some we have to build our own scatter/gather logic.

Item 2 could eventually be addressed by extending scatter/gather in V3 but item 1 can never be addressed by V3.

**Comment by sougou** [comment]
Coincidentally, this is what I'm going to work on next. It's also something that @demmer wanted.

**Comment by sougou** [comment]
These are the use cases I plan to address:
1. Allow a `shard` to be specified as part of any V3 request. If so, the `keyspace:shard` combination will cause that "target" to be treated as unsharded. This means that all unqualified table references will be auto-resolved to that shard, and since it's unsharded the restrictions will be lose (compared to queries that target sharded databases).
2. Any reference like `keyspace.table` will resolve using the keyspace qualifier and will therefore ignore the `keyspace:shard` of the request.
3. I'm thinking of extending the SQL syntax for table names to: `keyspace:shard.table`. For example, you can reference a table as `keyspace:-80.table`. This will be the SQL equivalent of targeting a shard without making it part of the request.

As per the above specifications, if you specified `keyspace:shard` in the request, and then used `keyspace.table` in your SQL, then the `keyspace:shard` of the request will be ignored. You must use the unqualified `table` or use `keyspace:shard.table` in the SQL to make it a single-shard query. If this won't suit people's needs, please respond, and we can discuss alternatives.

Additionally:
* If `keyspace:shard` is specified in the request, V3 will be changed to allow all DBA and DDL statements as pass-through.
* This pass-through will apply to unsharded keyspaces also.
* As an added bonus, queries to sequence tables will also be supported as pass-through.
* If no shard is specified, then the following limited support will be initially provided:
  * DDLs will be sprayed to all shards.
  * DBA statements will be forwarded to the first shard.

There is a long tail of improvements that can be added on top of this initial cut. For example, we can return aggregated info from all shards in the future, we can return alternate results if things don't match across all shards, and we'll also support extended DDL syntax for Vitess-specific features.

**Comment by derekperkins** [comment]
> 3. I'm thinking of extending the SQL syntax for table names to: keyspace:shard.table. For example, you can reference a table as keyspace:-80.table

I like that syntax. It's very similar to how BigQuery operates. `projectID:datasetID.tableID`

**Comment by demmer** [comment]
This seems great to me.

One thing that I will need (or would need to add on top of what you're doing) is support for this through the mysql server protocol implementation, so that I can connect to `keyspace:shard` as the database to which we connect, then query just on the table name to have it route to the specific shard.

**Comment by sougou** [comment]
Yes. If the syntax doesn't work for mysql protocol, we'll have to find an alternative.

**Comment by bbeaudreault** [comment]
Agreed this sounds great and I can use it for the liquibase work I was doing a couple weeks ago. But liquibase uses the qualified name iirc, so ideally it'd be configurable so that rule number 2 could optionally not apply. That is, allow qualified names to go through to the specified shard.

**Comment by sougou** [comment]
If shard was specified in the request, we could interpret `keyspace.table` as `keyspace:shard.table`. However, you'll have no way of addressing all shards of a table.

**Comment by bbeaudreault** [comment]
Shouldn't someone not use keyspace:shard if they're trying to address all shards of a table?

**Comment by sougou** [comment]
True. But it makes the model inconsistent. If your request contained `ks1:shard`, then `ks2.t2` would mean all shards of t2, whereas `ks1.t1` would mean `ks1:shard.t1`. It may lead to confusion.

**Comment by sougou** [comment]
Alternate approach:
If shard is specified, then all queries could be blind pass-through. Cross-keyspace queries will not be allowed. We can still allow table qualifiers, but they'll also be pass-through and must match the physical db name of the target shard. As an added bonus, this will allow you to run information_schema queries.

I think this will address all use cases. Let me know if something will get missed if we went this route.

**Comment by bbeaudreault** [comment]
That makes sense to me. Simple validation to ensure that an inconsistent/mismatch keyspace request doesn't come through.

**Comment by tirsen** [comment]
I kind of like the syntax but unfortunately your proposal is not going to work for us. :-)

Hibernate puts in the `keyspace.table_name` bit and it's not under our control. Occasionally we need to fire off some queries directly at a single shard and Hibernate will put in the `keyspace` prefix and there's nothing we can do about it. If Vitess would undo the single shard targeting the whole thing would just not work.

So I propose a slight change:
For untargetted requests keep the `keyspace.table_name` and `keyspace:shard.table_name` syntax as proposed.
For requests targetted at a single shard don't let the `keyspace.table_name` syntax loose the targetting. In fact, I think any table references outside the keyspace could be disallowed for targetted requests. The request targetting takes precedence over everything else.

**Comment by bbeaudreault** [comment]
@tirsen that sounds like @sougou's second proposal? Except maybe the addition of being able to specify keyspace:shard.table as a table name, which does seem nice

**Comment by tirsen** [comment]
Oh right! I only skimmed the thread and missed that.

Your last proposal would work @sougou except we would also need logical keyspace names as table qualifiers, not just the physical db name.

**Comment by sougou** [comment]
Accepting logical keyspace name would break the model though, as mentioned in the previous counter-point. But you should be able to easily work-around the db name issue right? The easiest one is to make the db name match the keyspace. It's a general guideline we follow internally also. Let me know if this will work for you.

**Comment by bbeaudreault** [comment]
@sougou any estimate on the timeline of the above being available in master? I've got WIP java changes to optionally skip V3 (https://github.com/youtube/vitess/compare/master...HubSpot:opt_skip_v3?expand=1), but it seems like this will supercede that by just allowing us to configure to use `keyspace:shard` in the JDBC options.  If it will be ready in the next week or 2 then I can just skip PRing the above and run my fork internally until it's ready.

**Comment by sougou** [comment]
I finally ramped up on the mysql protocol support for vtgate and have come up with a way to unify everything:
* Change VTGate.Execute to understand keyspace as `keyspace:shard`. There is not much value to adding a `Shard` field to the proto. The clients will anyway have to specify the db name as `keyspace:shard` which the drivers have to decode. Might as well pass it through and let VTGate.Execute decode it. This will allow the MySQL protocol to pass it through as well. We'll need to rename this field to indicate that it can contain a shard qualifier. Good thing we're using protos; Renaming is trivial.
* Change VTGate.Execute to understand `begin`, etc. If it encounters a `begin`, it can just start a transaction and return the session. On `commit` or `rollback`, the session will be reset. The clients are anyway wired to honor a returned session. This will also allow the mysql protocol to just pass the query through without the need to interpret it. Drivers that currently parse transactional statements will also be simplified. In the long run, we can look at dropping VTGate.Begin, etc. If we dare to be bold, we could even look at starting a new transaction if autocommit is off, pretty much mimicking MySQL.
* Add an `autocommit` field to VTGate.Session, and have VTGate.Execute turn it on if a `set autocommit=1` is issued. If not in transaction and the flag is on, a new transaction will be started for each DML, and committed or rolled back at the end, just like MySQL. This will allow us to deprecate vttablet's (dangerous) autocommit.
* Since the MySQL protocol is expected to gain popularity, I'm thinking of switching the `normalize_queries` flag to true, which will save CPU.

**Comment by sougou** [comment]
@bbeaudreault You can drop that. I think my stuff will be done this weekend.

**Comment by bbeaudreault** [comment]
@sougou awesome. I'll simplify my code then. I also found a JDBC bug which I fixed above, so will submit that separately and throw the rest away.

In terms of the new plan sounds good to me, especially (i think, if i understand it correctly) the autocommit functionality. I think it would be good to have a way to enable autocommit as an ExecuteOption too, for drivers and such. In the oracle mysql java driver it executes `set autocommit=1` once per connection. Since we don't have stable connections, we'd need to set it per request.

**Comment by sougou** [comment]
The autocommit design is meant to survive reconnects. That's why I'm making it part of Session.

**Comment by bbeaudreault** [comment]
@sougou and I discussed offline. When his changes are available I'm going to modify the JDBC to support caching the Session on the VtGateConn, similar to how VtGateTx works.  When someone calls `setAutoCommit(true)`, we will send a `vtGateConn.execute("set autocommit=1")` and the resulting Sesion will be used for all future vtGateConn calls.  VtGateTx will still create it's own session for now when Begin() is called. This is fine because an explicit connection does not care about the value of autocommit. If in the future we add other fields to the Session that do impact a transaction, we'd need to modify Begin() to pass in the existing session or deprecate Begin() in favor of calling `vtgateConn.execute("begin")`

**Comment by michael-berlin** [comment]
re: the `keyspace:shard` syntax.

I don't like that we would have two different styles to express a shard in a keyspace. All our admin tools expect `keyspace/shard`.

Personally, I actually like the `:` over the `/` but I think the inconsistency is going to be confusing in the long term.

Are database names with a `/` in it going to be a problem in external tools e.g. when they parse URLs? Creating such a database with a quoted identifier seems to work though:
```
MariaDB [(none)]> create database `ks/shard`;
Query OK, 1 row affected (0.01 sec)
```
If I read https://dev.mysql.com/doc/refman/5.7/en/identifiers.html correctly, both `:` and `/` should be allowed in quoted identifiers (they're within the unicode ASCII range U+0001 .. U+007F).

What do our external users think?

**Comment by demmer** [comment]
If it's all the same to the implementation I would prefer @michael-berlin's suggestion of sticking with the consistent syntax of `keyspace/shard`.

**Comment by sougou** [comment]
The problem with `/` is that it's also an operator. So, `keyspace/-80` has multiple interpretations. This means that you can't use it in a SQL construct without backquoting. But I think it's a minor inconvenience.

So, for now, I'll switch to `/`. We can always additionally support `:` in the future if `/` becomes a problem.

**Comment by sougou** [comment]
Addressed via #2646

**Comment by tirsen** [comment]
Is this supposed to work now and what exactly is the syntax? I'm trying the following but it doesn't work:
```
> vtctlclient -server $VTCTLD VtGateExecute -server $VTGATE 'select count(*) from mykeyspace/0.mytable'
E0511 16:18:21.298121  178671 main.go:43] Remote error: rpc error: code = 2 desc = Execute failed: vtgate: http://.../: syntax error at position 40```

**Comment by sougou** [comment]
@tirsen Single shard targeting currently works through session level db specification. You have to `USE mykeyspace/0` and then execute `select count(*) from mytable`.
The `USE` statement just sets the target_string of the session: https://github.com/youtube/vitess/blob/master/proto/vtgate.proto#L76. This is something you can also directly set from the client side. It's typically the dbname of a connection parameter.
That is how I believe @bbeaudreault would implement it for the Java API.

**Comment by bbeaudreault** [comment]
Yep. ExecuteRequest.setKeyspaceShard will be replaced with the Session object. Session object will effectively be per VitessConnection.

I'm going to be working on this very soon now

**Comment by tirsen** [comment]
So I can't use this from `VtGateExecute`?

Will this `USE` syntax also take `served_from` into account? That is, in preparation for a vertical reshard will I be able to target a new keyspace and have it served from an existing shard? The V2 single shard targeting doesn't handle that properly.

**Comment by sougou** [comment]
@tirsen I realize that you're talking about vtctld VtGateExecute? If so, you should be able to specify `-target='keyspace:shard@replica'`. And it should resolve correctly to the `served_from` setting. Let me know if it doesn't. If you specified a shard, the implementation essentially redirects to V2. Otherwise, it's a different code path, but it should still honor `served_from`.

**Comment by tirsen** [comment]
Sorry I'm still confused by all this. :-)

What exactly is the new syntax introduced by this? Both to set target shard on session level and on individual statements. Can you provide a few examples? Are there documentation for this somewhere?
