### ISSUE TITLE
testing an insert statement with fakevitess

### ISSUE THREAD

**Issue by moeinrahimi** [youtube/vitess#2643]
hi i'm trying to test an insert statemnt using fakeVitess, but i'm stuck because my sql values are different from my test file and [fakeVitess](https://github.com/youtube/vitess/blob/608ffcc264e64a77dc2cdcb728697b0702f69833/go/vt/vtgate/fakerpcvtgateconn/conn.go) is expecting the exact same data. is there any way to say don't care what the data is going to insert ?

this is my code
```
func createDetailsQueries(conn *fakerpcvtgateconn.FakeVTGateConn) {

	fields := []*querypb.Field{
		&querypb.Field{
			Name: "username",
			Type: querypb.Type_CHAR,
		},&querypb.Field{
			Name: "password",
			Type: querypb.Type_CHAR,
		},&querypb.Field{
			Name: "salt",
			Type: querypb.Type_INT64,
		},
		
		&querypb.Field{
			Name: "status",
			Type: querypb.Type_CHAR,
		},
	}
	var username string = "moein"
	var status string = "ACTIVE"
	var password string =     "1"
	var salt string
	var err error
	salt,err = security.GenerateSalt(2)
	fmt.Print(salt)
	password,err = security.EncodePassword(password,salt)
	resultMatch := &sqltypes.Result{
		Fields:       fields,
		RowsAffected: 0,
		InsertID:     0,
		Rows: [][]sqltypes.Value{

			//[]sqltypes.Value{},
			[]sqltypes.Value{
				sqltypes.MakeString([]byte("moeihfhfghn")),
				sqltypes.MakeString([]byte("ACTIVE")),
				sqltypes.MakeString([]byte(password)),
				sqltypes.MakeString([]byte(salt)),
			},
		},
		Extras: nil,
	}

	//var adminId int64 = 12
	//var adminCoins int64 = 20002
	//var adminEmail string = "admin@qok.com"
	//var score int64 = 2002
	//var level int64 = 34
	//var username_change_time int64 = 3
	//var weekly_score int64 = 5002

	if err != nil {
		panic("err while encoding in fakevitter-user")
	}
	session := &vtgatepb.Session{
		InTransaction: true,
	}
	conn.AddQuery(user_model.CreateUserQuery,
		map[string]interface{}{"username":username,"password":password,"salt":salt,"status": status}, topodatapb.TabletType_MASTER, session, false, resultMatch)



}
```

**Comment by michael-berlin** [comment]
Can you please describe what you're trying to achieve?

I assume you're writing application code which uses the Go Vitess driver and tries to talk to Vitess? And now you want to verify that your code is returning the correct queries?

In general, we recommend to write tests against the real thing and not a fake or mock. In fact, the `FakeVTGateConn` you referenced is basically no longer used in our code (except for one special use case) because we usually use the real object.


**If you want to test the actual functionality, I recommend the `vttest` Go package for Go tests.**

It allows you to launch both Vitess and MySQL. Here's an example: https://github.com/youtube/vitess/blob/608ffcc264e64a77dc2cdcb728697b0702f69833/go/vt/vttest/local_cluster_test.go#L39

The "vttest" Go package is a wrapper for the "run_local_database.py" script: https://github.com/youtube/vitess/blob/master/py/vttest/run_local_database.py

That script does all the magic for you: It launches MySQL and all Vitess components. Note that the Vitess components are run as simplified binary "vtcombo" which combines vttablet, vtgate and vtctld.

See also: http://vitess.io/user-guide/scalability-philosophy.html#development-workflow

Within this test "cluster", Vitess Keyspaces and shards are mapped to separate databases and run on a single MySQL instance.

The "run_local_database.py" script supports arbitrary setups of keyspaces and shards. For starters, the simple example in local_cluster_test.go should be good enough. (Keyspace "test_keyspace" with a single shard "0".) If you want to specify more complicated setups, feel free to look at the documentation of the configuration protobuf: https://github.com/youtube/vitess/blob/master/proto/vttest.proto

When using the script, we recommend to use the `--schema_dir` command line flag to point it to your schema .*sql files. More generally, we suggest to have your MySQL schema definitions in the same Git repository as your code such that your test can reference it. The `--schema_dir` flag is accessible in the "vttest" Go package via the "SchemaDirectory" option: https://github.com/youtube/vitess/blob/608ffcc264e64a77dc2cdcb728697b0702f69833/go/vt/vttest/local_cluster.go#L76

@alainjobart can you confirm that this makes sense?
