### ISSUE TITLE
ApplySchema printing incorrect messages

### ISSUE THREAD

**Issue by ashudeep-sharma** [youtube/vitess#2674]
Team, we were trying to add an index to the table by using ApplySchema -allow_long_unavailability flag. We are getting the following messages when executing the commands for each shard:

**W0324 02:00:52.752605   14093 main.go:40] W0323 20:30:52.751809 tablet_executor.go:117] Processing big schema change. This may cause visible MySQL downtime.**

**W0324 02:02:17.999586   14093 main.go:40] W0323 20:32:17.999089 schema.go:81] Failed to reload schema on slave tablet nm-0000000007 in srms/-40 (use vtctl ReloadSchema to try again): rpc error: code = 2 desc = TabletManager.ReloadSchema on nm-0000000007 error: timed out waiting for position 0cd73273-7e40-11e6-8a1d-02010a5593b4:1-224075571,0d1710c6-7e40-11e6-8a1d-02010a558ec3:1-31290882**

However we validated that the schema change is correctly applied on Master as well as slave instances without even executing the ReloadSchema on slave tablets.

Its a 4 shard setup with approx 4.7 million entries per shard making a total of around 18 million entries.

**Comment by sougou** [comment]
Looks like the default timeout for replica wait is 10 seconds https://github.com/youtube/vitess/blob/master/go/vt/wrangler/schema.go#L31. So, if the apply to longer than that, you're likely to see that error. But the replicas should eventually catch up.

Do you know how long the apply took to execute? You can retry a similar schema change, but specify an explicit timeout that's at least twice as long (wait_slave_timeout).

Beyond this, I'll defer to @michael-berlin.

**Comment by alainjobart** [comment]
Workaround: technically, the ReloadSchema call just makes sure the slaves
are past the GTID of the schema change, and then issues a ReloadSchema to
the tablet. If you are sure the schema is applied on all the tables, you
can manually run a ReloadSchema, and then you'd be good. Or just wait for
the refresh period for the tablets to pick it up.

(i'm surprised though, so many of your slaves are more than 10s behind on
replication?)

**Comment by michael-berlin** [comment]
Alain, waiting for the slaves probably took longer because the schema change itself took ~2 minutes. The slaves have to execute it as well and therefore you would have to wait for the same time there?

Sounds to me like we should automatically increase the default wait time in case of a big schema change.

@alainjobart and @sougou, another question to clarify: If vttablet is running with `--watch_replication_stream`, the reload would not be necessary, right?

@ashudeep-sharma You said that the change was applied on the slaves. That's expected because MySQL replication takes care of it. However, vttablet must reload the schema as well or it won't recognize e.g. new columns. By default, vttablet automatically reloads the schema every 30 minutes (`--queryserver-config-schema-reload-time`). The explicit reload at the end of ApplySchema makes sure that it happens right after the change on all tablets. I'm considering to clarify the error message to make it clearer that the schema change was successful but the reload failed.

**Comment by ashudeep-sharma** [comment]
Thanks for the details, @michael-berlin clarified the part of it, our schema change definitely took more time than the default timeout . This issue came in from one of the teams which are trying the system in production so i am not sure by what time the change got propagated to the slaves. The only thing is that they didn't execute Reload Schema.
@michael-berlin : I think clarifying the error message will work here so that it doesn't create any confusion.

**Comment by alainjobart** [comment]
What do you think is missing from the error message?

It is now:
Failed to reload schema on slave tablet nm-0000000007 in srms/-40 (use vtctl ReloadSchema to try again)

Maybe mention something like 'queries using the new schema may fail until schema is reloaded'?

**Comment by ashudeep-sharma** [comment]
@alainjobart : There are two issues here, first of all in using -allow_long_unavailability field should we  
I don't have the exact console messages but I believe for long running Admin commands which have multiple steps we should print information like this:
Schema Change Applied Successfully on Master[tabletId]
.....
**Schema Change Applied Successfully on Slave[tabletId]** 
**OR**
**Failed to reload schema on slave tablet nm-0000000007 in srms/-40 (use vtctl ReloadSchema to try again), queries using the new schema may fail until schema is reloaded**

Using this format a user can be sure where the schema has been applied and what next steps needs to be done.

Another part which i was thinking is that currently the default value of wait_slave_timeout has been set to 10 seconds, shouldn't it be something like <SchemaApplyTimeonMaster> + 10 ?

**Comment by sougou** [comment]
I kept this bug open because I wanted to remove the warning, because made it look like the schema apply failed.

However, looking at it again, I think the warning should stay because it may be actionable under some situations. For example, the user may choose to wait till the schema apply completes on the replica, and then issue a manual reload.

So, I'll close this if there are no objections.
