### ISSUE TITLE
Heartbeat support in vttablet

### ISSUE THREAD

**Issue by bbeaudreault** [youtube/vitess#2687]
It's well known that the slave last returned by `SHOW SLAVE STATUS` can be misleading or incorrect in some circumstances, such as when writes have stopped or the SQL thread is having issues. [pt-heartbeat](https://www.percona.com/doc/percona-toolkit/2.1/pt-heartbeat.html) is a tool out of percona for measuring the actual lag as determined by real reads and writes.

The basic premise is that on the master side you update a row in a table with the current timestamp. On the slave side, you read from the table and compare the timestamp to now. This determines your slave lag.

This value can be published to the monitoring endpoints, and can be used to more accurately determine whether a tablet is healthy enough to serve reads. This also allows operators to remove one more daemon when moving to vitess, which is a definite bonus.

cc @michael-berlin @alainjobart @sougou

**Comment by alainjobart** [comment]
To comment a bit more on this, and what the implementation would probably look like:

* we can add a flag to vttablet, and when the tablet becomes master, we can start a heartbeat routine (we already start routines when becoming master to handle message queues). The heartbeat routine would make sure the heartbeat table exists (or create it), and periodically update a record in there. Every second or more frequently if needed. (let's use a storage column more granular than second in any case). This table should be in the _vt database.

* on slave vttablets, we just need to implement another health check plugin, that looks at the table and reads the value instead of getting the 'show slave status' result. The plugin now is at second granularity, might want to change the interface to return a time.Duration, instead of an int (seconds).

* filtered replication also has a 'seconds behind master' field. Although we could possibly forward the heartbeat messages from source shard to destination shards, I don't think it should be changed, that's a bit more complicated for not much.

All in all, this shouldn't be a big change at all.

**Comment by bbeaudreault** [comment]
I'm working on this now.

**Comment by bbeaudreault** [comment]
This was fixed by https://github.com/youtube/vitess/pull/2746

You can enable this by using the vttablet commandline argument `-heartbeat_enable`. The default interval for sending and checking heartbeats is 1s, which you can change with `-heartbeat_interval`
