### ISSUE TITLE
Schema Swap workflows issues

### ISSUE THREAD

**Issue by adkhare** [youtube/vitess#2758]
@pivanof 
We tried schema swap tool for the first time over this weekend. Overall, the tool is great. However, we have been facing some of the issues which are following:

1. During the failures (normally on the backups due to Google API/Network issues), backups may fail. However, Applying schema on seed is completed. Can we retry only the failure steps rather than retrying every step again?
2. Some shards complete the steps of applying schema faster than other shards. Can we have a way to go ahead with next steps on the specific shard rather than waiting on other shards to complete the current step?
3. During the backups, what is the concurrency set? I am assuming, its default. Is there a way to configure that?
4. Can we add 3 retries on the failures like backup failures?

Lets talk on slack if you need any details on the same. We are trying to move faster with the schema changes and following are the items that may lead us to block.

Thanks & Regards,
Amit Khare

**Comment by pivanof** [comment]
1. The schema swap workflow is written in a way that it doesn't retry steps that are not necessary. So when backups fail and you retry the whole workflow it won't apply the schema changes again because it will determine that there are replicas with the new schema already (assuming they came back online after the failed backup).
2. This restriction is made deliberately to not start propagating schema too fast in case it will be determined that on one shard it's infeasible to do the schema change (e.g. unique index cannot be created due to duplicate data). In such case it's much easier to rollback if the backups were not taken yet.
3. The flag is -schema_swap_backup_concurrency. The default is 4.
4. Why? As I pointed above retrying the whole workflow (or even deleting the workflow and creating it again) should work pretty much the same way (except that it will retry backups on all shards).

**Comment by adkhare** [comment]
So, for the backups, as you said, it will take backups even if its successful before. is there any reason(apart from getting the latest data and save time for catch up) why the backups are taken again?

**Comment by pivanof** [comment]
The reason is that there's no API to understand whether the latest backup contains the schema change or not. When a new backup is taken from the replica that is determined to have the new schema, then it will be known that it contains the new schema and is suitable for the new schema propagation.

**Comment by adkhare** [comment]
ok sounds good.

**Comment by pivanof** [comment]
As I understand there are no AIs left here. Closing the issue.
