### ISSUE TITLE
Support tablet and mysqlctld in different Docker containers

### ISSUE THREAD

**Issue by nizsheanez** [youtube/vitess#2868]
Right now it's impossible to specify mysqlctld host in tablet parameters. 
Tablet using `-tablet_hostname` as host of master db.  
It's mean if tablet and mysqlctld are in separated docker containers - replication can't work because Slave trying to connect to tablet hostname instead of mysqlctld hostname. 
Related Code: https://github.com/youtube/vitess/blob/master/go/vt/vttablet/tabletmanager/init_tablet.go#L135

**Comment by sougou** [comment]
@alainjobart @michael-berlin 
Chasing down the usage of this variable, I see that it's used in commands like this https://github.com/youtube/vitess/blob/master/go/vt/vttablet/tabletmanager/restore.go#L174, which causes mysql to connect to the vttablet host instead of the mysql host. We probably need to see if we have to introduce a separate mysqlHost variable (or reuse it from somewhere else).

@nizsheanez 
The work-around for now is to set up the replication relationships yourself. But you should still be able to use vttablet for query routing etc.

**Comment by sougou** [comment]
@nizsheanez This should work now.
