### ISSUE TITLE
default tx pool limit of 20 transactions too low and error message confusing

### ISSUE THREAD

**Issue by alouane** [youtube/vitess#2965]
Hi there,
I ve juste noticed many of this error inside a tablet's log file

![image](https://user-images.githubusercontent.com/3225153/27512965-94bbec24-5943-11e7-823d-9c6c4c25339d.png)

+ there is a `pool connection limit exceeded` error too, I believe this is related to the `queryserver-config-transaction-cap` server parameter, but can someone point me where I can tune this parameter up, is it inside the vttablet pod yaml file? if yes how to update a vtablet running in a production environnement?

Thanks

**Comment by sougou** [comment]
Hi Alouane, you can add that argument to vttablet anywhere here: https://github.com/youtube/vitess/blob/master/examples/kubernetes/vttablet-pod-template.yaml#L50. We typically recommend a pool size in the low hundreds, but the actual number can vary widely depending on your use case.

**Comment by alouane** [comment]
Ok cool, thanks sougou

So my question now is, how to perform a safe update to all pod tablets currently running in a prod environnement?
I'm not sure if taking a tablet backup => then tearing down all vtablets => then recreate new onces that will grabe the last backup from aws s3
I think some records will be lost during this period of time
Do you think I need a rolling update using the replication controller?

Thanks

**Comment by sougou** [comment]
I think there are others who can answer this better. In general, a rolling update is what would be recommended. But I'm not sure about the exact details.

If kubernetes allowed it, an in-place restart of vttablet is pretty fast, but I heard it kills the pod if you tried this.

**Comment by michael-berlin** [comment]
I also don't know the answer. Maybe @enisoc can help out?

> If kubernetes allowed it, an in-place restart of vttablet is pretty fast, but I heard it kills the pod if you tried this.

That's also what I remember: after a restart, vttablet will restore from the latest backup. Everything which has changed since the backup was taken will be streamed from the current MySQL MASTER. Therefore, it's important that you don't restart all vttablet instances at once and always leave some up who can remain the MASTER and stream the changes since the last backup.

This type of deployment makes sense if you run many MySQL replicas in different data centers world wide and it's very unlikely that all replicas go down at the same time.

In practice this means that smaller setups should not use this type of setup. To address this concern, @enisoc also added support for Kubernetes' [StateFulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) which was recently added to Kubernetes. However, this doesn't work with the `examples/kubernetes` templates. Instead, you have to look at the new Vitess Helm chart in the `helm` directory. It looks like this is the place where you configure the StateFulSet: https://github.com/youtube/vitess/blob/master/helm/vitess/values.yaml#L127

We plan to replace the current Kubernetes example templates with the new Helm Chart and only keep that. The work for that is tracked here: https://github.com/youtube/vitess/issues/2771

If you're wondering what Helm is, let me quote the (Helm README](https://github.com/kubernetes/helm):

> Helm is a tool that streamlines installing and managing Kubernetes applications. Think of it like apt/yum/homebrew for Kubernetes.

@enisoc can you comment how feasible it would be to migrate an existing deployment, based on the example templates, to the new Helm chart?

**Comment by michael-berlin** [comment]
I've renamed the bug title to better reflect the problem here.

The `unsecure_grpc_client` text you see in the logs is not an error: If the transaction pool hits the limit of, by default 20, concurrent transactions in flight, and new transactions get rejected, it logs the current pending transactions. You should see 20 pending transactions logged, one transaction per line. For each transaction we also log its [`CallerID`](https://github.com/youtube/vitess/blob/7af23e1ddecff76a558c93e3e49ae1a899011662/proto/vtrpc.proto#L25). In the open-source default setups the caller id has only the text `unsecure_grpc_client` in it and that's what you see in the logs. You could set the CallerID e.g. based on the Common Name of certificates or what your application provides. Details are documented here: http://vitess.io/user-guide/transport-security-model.html

**Comment by alouane** [comment]
Ok I see, thanks for explanation guys

That maybe explains then the inconsistency that I saw between a statistics framework & what the vitess database was recording => a lot if transactions were rejected

So I guess this php error is definitely also related to this transaction limit issue `"PHP message: PHP Fatal error:  Uncaught Vitess\Exception: rollback called while not in transaction. in .../vendor/vitess/php-client/php/src/Vitess/VTGateTx.php:194`
right?

Also I believe failed transactions are being restarted:
`tabletserver.go:1172] Lock wait timeout exceeded; try restarting transaction (errno 1205) (sqlstate HY000)`

How many times the transaction get restarted? is there any limit? & is there any chance the transaction get lost & data not recorded in the database?

Thanks

**Comment by alouane** [comment]
Hi
I ve noticed that after updating the `queryserver-config-transaction-cap 100` parameter => the master reported a lot of `too many connections` errors

![image](https://user-images.githubusercontent.com/3225153/27518008-9fa3d17e-59c5-11e7-9662-b677aa2f4e20.png)

Do you think 100 value as a transaction cap limit is very low or is it related to server capability?

& is it possible to make live edits for these server query parameters => somewhere inside the kube pods 
`kubectl exec vttablet-100 -c mysql -t -i -- bash -il`

instead of killing the pod each time then recreating it

Thanks

**Comment by sougou** [comment]
MySQL also has a very low connection limit by default: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_connections. You'll need to increase that.

**Comment by sougou** [comment]
The PHP error you see is likely a symptom of the transaction having been previously rolled back, likely due to a timeout. You can increase the transaction timeout with the flag: `-queryserver-config-transaction-timeout`. The kubernetes examples are for test environments. Take a look at http://vitess.io/user-guide/server-configuration.html for what would work in production.

**Comment by enisoc** [comment]
@michael-berlin wrote:
> I also don't know the answer.

And yet the answer you gave is correct. :)

Some additional details:

* With `examples/kubernetes` configs:
  * Delete and recreate vttablet pods one at a time by hand, ensuring each one becomes healthy before moving on to the next one.
  * This configuration uses a local `emptyDir` volume, so when the pod restarts it will have to do a full restore from backup.
* With `helm/vitess` chart in StatefulSet mode:
  * Update vttablet flags/image via `values.yaml`, then use `helm upgrade` to post the new pod template. Delete the vttablet pods by hand one at a time, then wait for the StatefulSet controller to recreate each one with the new pod template. Wait until each tablet goes healthy before moving on to delete the next one.
  * If you use the Vitess Helm chart in PersistentVolume mode (see `values.yaml`), each tablet's data will survive the update, so they will not need to restore from backup.
  * Note that in the upcoming Kubernetes 1.7 release, StatefulSet can do an automatic rolling update for you.

> can you comment how feasible it would be to migrate an existing deployment, based on the example templates, to the new Helm chart?

It would be tricky... If you're ok with downtime, you could probably set all masters read-only, take backups, then tear everything down and bring it back up with the chart instead. To do it live would require a lot more planning.

**Comment by alouane** [comment]
Thanks guys for the infos, I managed actually to get the system running during live update & tuning of the database using a third party stats framework

But I want to check with you guys about this`queryserver-config-transaction-cap`  parameter
I ve tested several values (100, 200, 500, 800, 1000), and unfortunatlly all possible values failed once I switch the server to production first stage (200 write query per second) => I got the same `Too many connections` issue
But once I ve deleted that parameter, the server got back to normal => no too many connections issue
However, increasing the mysql max_connections value did the trick => no `pool connection limit exceed` issue

My current issue now is with this `mysql server has gone away` => I found that it could be related to `max_allowed_packet` or `open_files_limit` parameters. Is there somewhere I can deeply debug this issue?

![image](https://user-images.githubusercontent.com/3225153/27552841-518042e2-5a98-11e7-83bf-6824aa32f03a.png)

**Comment by sougou** [comment]
The 'gone away' errors are because your call to begin are getting killed, which is very strange. Begin should never hang.
Have you increased your mysql connection limit (from 150 to a number much higher than the pool sizes)?

Your transaction pool size should be approximately the number of concurrent transactions you're expected to have, which is a function of average transaction time and transactions/sec. So, if your transaction qps is 300, and each transaction is 1s, then your pool size should be at least 300.

**Comment by alouane** [comment]
Yeah I ve tweaked these parameters too, but I believe something is not straight with my kubectl setup that is using most cluster's memory, so I ve to look deeper into my setup

Feel free to close this issue :) 

Thanks again for the infos guys, I appreciate it
