### ISSUE TITLE
vtexplain: tool to simulate vitess query plans

### ISSUE THREAD

**Issue by demmer** [youtube/vitess#3062]
# Motivation and Overview

Understanding how vitess handles a given SQL query is a big challenge for users that are considering converting to vitess. This is an issue because the set of queries which are eventually run on the mysql instances depends on the vschema, the underlying sql schema, other factors like the replication mode and vtgate transaction mode, and of course whether or not vitess currently implements support for the given query.

To address this, we're proposing a new offline query analyzer tool called `vtexplain`. Given a vschema, sql schema, and a set of sql queries, it simulates the vitess execution flow from gate to tablet to mysql and shows the actual queries that would be executed on each mysql shard.

This allows developers to understand not only which queries are compatible with the vitess parser, but also explore the impact of various sharding strategies, replication modes, etc on the subsequent query plans.

# Example

As an example, a bulk insert on the user table in the example schema would be output as follows:

```
# ./vtexplain -shards 16 -replication-mode "ROW" -schema-file example.sql -vschema-file example.json -sql "insert into user (id, name) values(1, 'alice'), (2, 'bob'); select count(*) from user where id in (1,2)"

----------------------------------------------------------------------
insert into user (id, name) values(1, 'alice'), (2, 'bob')

[ks_sharded/10-20]:
begin
insert into user(id, name) values (1, 'alice')
commit

[ks_sharded/40-50]:
begin
insert into name_user_map(name, user_id) values ('alice', 1)
commit

[ks_sharded/d0-e0]:
begin
insert into name_user_map(name, user_id) values ('bob', 2)
commit

[ks_sharded/-10]:
begin
insert into user(id, name) values (2, 'bob')
commit

----------------------------------------------------------------------
select count(*) from user where id in (1,2)

[ks_sharded/10-20]:
select count(*) from user where id in (1) limit 10001

[ks_sharded/-10]:
select count(*) from user where id in (2) limit 10001

----------------------------------------------------------------------
```

The tool also supports a more detailed json output that shows details of the vtgate query planner as well as the bind variables sent to each tablet.

# Implementation

The implementation combines the vtgate query executor, a fake topology engine, the vttablet query executor, and the fake mysqldb into a new target binary. For the most part, the simulation harness already existed for the unit tests of each component, which can be combined into this process. The tool first parses the vschema and schema, sets up the fake tablet topology, runs the query through vtgate to find the set of queries and bind variables that are run at each tablet, and for each of those, runs them through the tablet executor to find the queries processed by mysql.

The most impactful change required for this work is to extend the sql schema to handle `CREATE TABLE` DDL statements. This is needed so that the fake mysql engine can be configured with all the information schema queries needed for the tablet to know the full sql schema. This carries with it some risk, since the existing schema blindly accepts anything after `CREATE TABLE tablename` and passes them through for the `ApplySchema` command.

Since these are fairly substantial changes, I'm going to split them up into multiple PRs:

1. Schema changes to fully support create table (#3067) ✅ 
~2. Changes to vtgate and vttablet needed to support vtexplain (#3068)~ merged with #3082
3. The vtexplain tool (#3082)

I'll update this issue with links as I carve up the individual PRs, but am opening this issue for general feedback before polishing up the rest of the implementation.

**Comment by bbeaudreault** [comment]
I'm very, very interested in this, thanks for tackling! It's been on my long term bucket list for a while.

We hope to hook something like this up to our java unit tests which currently run against an EmbeddedDataSource (mysql_embedded). We already have the harness in our tests for creating an embedded datasource using the java lib's MysqlResource. It creates a fully functional embedded database which is available on localhost at a given port. Our tests are all set up to execute any schema changes against this database. We'd love to be able to wrap that in a vitess binary so that existing SQL-related tests can be transparently validated against a vitess-backed mysql.

It's possible I require a totally separate binary for my requests below, with a different purpose and it's not worth muddying vtexplain. So feel free to push back, but here's what would be great for my use case:

- Allow pointing at an existing mysql address/port instead of requiring a schema file
- Make the vschema file optional
- If possible, allow a mode where the vtgate actually listens on grpc and vttablet actual executes against the configured mysql.

If this is too much for vtexplain, I can hold old off and re-use some of your implementation to create a new binary for this purpose. I think it would overlap a lot of what you'll be looking to do.

**Comment by demmer** [comment]
@bbeaudreault Glad to hear you're interested and as far as I'm concerned, the more eyes on vtexplain the better :) I'd love for this to get put through the ringer by folks outside of slack.

As far as the specific suggestions go, how about we wait until I can wrangle a couple PRs together and then see how disruptive it would be to make these changes as opposed to you cutting a new binary.

In particular, the first two seem totally straightforward. However that last one sounds a lot like the existing `vtcombo`, unless I'm missing something.

**Comment by sougou** [comment]
@demmer I assume this is now resolved. Feel free to close.
