### ISSUE TITLE
Reset sequence caches after losing MASTER

### ISSUE THREAD

**Issue by tirsen** [youtube/vitess#3116]
You have two vttablets: A and B.
A is MASTER and has a sequence with a cached value.
Now do TabletExternallyReparented and B becomes MASTER.
B now caches the sequence value and starts incrementing.
Reparent back to A.
A will now re-use the old cached sequence value and will start handing out overlapping sequence numbers causing all sorts of constraint violations.

Fix: Tablet A should be dropping its cached value for all sequences upon losing MASTER

**Comment by alainjobart** [comment]
I agree with the fix.

There is the corner case when upon reparenting, the old master doesn't get the message that it lost its mastership. After @pivanof fix to make it more reliable, I am wondering how often it still happens.  Because in that case, the old master doesn't know it's not the master any more, and when gaining mastership back, would not clear its cache.

**Comment by sougou** [comment]
@alainjobart do you know the PR number? Is that the case where a tablet is set back as master due to a failed reparent, it never transitions to a replica? I'm wondering it it fixed #2850 also.

The specific case of dropping the cache on losing mastership should be relatively easy. But I'll have to see if the sequence generator should be exposed as a module. That way, the control will be at the tabletserver level. I'll need to look at the code.

**Comment by tirsen** [comment]
There is definitely a possibility of the old master not being notified in case of network partitioning. That said, it's rare and the fix would certainly be an improvement of what we have now which is broken 100% of the time.

Maybe the tablet should also listen to its assignment through Zookeeper? That way it would be eventually notified of a reparent? (Zookeeper usually fans out notifications very quickly, unless something is broken.)

**Comment by alainjobart** [comment]
Just to be clear, I completely agree with this fix, it needs to be done. @sougou can probably handle it from Amsterdam. ;)

The PR from @pivanof was this one: https://github.com/youtube/vitess/pull/2978 and it fixed the use of the wrong context when the new master talks to the old master. After that fix, hopefully, there won't be many cases when the old master is not reachable.

We do have a protection in vttablet to make sure the tablet record has not been modified by anyone else than the current owner (tabletmanager remembers the topology server version of the tablet record). In the case where the new master cannot reach the old master, it should instead set the topo record old the old master to replica. Then when the old master tries to change its record after that, it should notice something happened, as its version would not match. But that check would only happen the next time the old master tries to update its topo record, which may not be for a while. Anyway, I'm not sure there's anything we can do. Let's fix this bug first, and then see if we need to do more.

**Comment by sougou** [comment]
I handled it over the Pacific instead.
