### ISSUE TITLE
Vitess JDBC driver and dependencies

### ISSUE THREAD

**Issue by vsabella** [youtube/vitess#3124]
The Vitess JDBC driver contains numerous dependencies some of which have binary conflict with our other platform components. Netty and Guava mismatches are the first which come to mind.

Is there any reason why Vitess JDBC driver cannot be fully shaded with relocation/rewriting to avoid these dependencies mismatches?

**Comment by michael-berlin** [comment]
After reading:

* https://softwareengineering.stackexchange.com/a/351091
* https://www.elastic.co/blog/to-shade-or-not-to-shade

I'm reluctant to do this. Based on the reading, shading i.e. providing a fat jar with renamed classes to avoid collisions, brings its own problems and makes it harder to debug issues.

I'm surprised this hasn't been a problem before for others?

It sounds like the alternative is that you do the shading on your end?

If it makes sense to upgrade some of our dependencies e.g. because they're way behind popular versions, I'm happy to do this. For example, gRPC was recently bumped from 1.0 to 1.5.

**Comment by bbeaudreault** [comment]
I don't think we should shard the driver. We can potentially provide a separate artifact that is pre-sharded. Some other projects provide that. Sharding is generally not ideal if it can be avoided because if every dependency one used was sharded we'd have multi-GB jars. Also having vitess determine how to shard is enforcing a jar configuration on everyone. 

At hubspot we shard the vitess driver but that's what makes sense for our environment. We also relocate and add some additional files that may not make sense for vitess to do for everyone. 

I could PR a simpler shaded artifact based on ours next week if there's interest.

**Comment by sougou** [comment]
I assume this is resolved. I'll close this if there are no further updates.
