### ISSUE TITLE
udpate/delete  with routing key in parentheses not supported

### ISSUE THREAD

**Issue by xhh1989** [youtube/vitess#3283]
I encouter a problem, udpate/delete  with routing key in parentheses not supported.
       for example I have a table messages with route key page, sql like this : delete from messages where page = 1 is ok, but delete from messages where (page = 1) is not supported (unsupported: multi-shard where clause in DML).
   I use third party client which generate sql like where (page=xxx) and (xxx) and ...., Is there any other suggests to resolve this problem?

**Comment by sougou** [comment]
This new PR should address your use case.
Changing splitAndExpressions wouldn't have helped the above use case because the DML analyzers don't use that function. Also, the analysis of `where` and `having` clauses already drill down into parenthesized expressions. So, it wouldn't have helped there either.
In this fix, I've changed it such that the analyzers drill down instead of stripping parenthesis from the AST. So, this should overall work out better.

**Comment by xhh1989** [comment]
yes, it works well, thank you !
