### ISSUE TITLE
Running SplitClone fails with grpc transport errors

### ISSUE THREAD

**Issue by sjmudd** [youtube/vitess#3412]
I've run this before a couple of months ago and it seemed to work fine but now I'm unable to run SplitClone without triggering failure. I can't identify the cause.

The intention is to reshard from `keyspace/0` (taken from production slaves) to `keyspace/-80` and `keyspace/80-` which are empty and configured ready to take the data.

## Environment

* CentOS 7
* tried with go: versions 1.9 / 1.9.2
* Vitess build commit e784ac3db372c4b1dc5a652dae7f64d11bc1ac84
```
# Merge: 8a5d0b3b1 a7a8ee578
# Author: Alain Jobart <alainjobart@gmail.com>
# Date:   Wed Nov 22 07:52:37 2017 -0800
#
#     Merge pull request #3402 from alainjobart/simpletopo
#
#         Simplifying topo implementations.
```

## Servers in environment

```
$ vtctlclient -server :15999 ListAllTablets cell1
cell1-0000000100 keyspace -80 master db-009:15302 db-009:17201 []
cell1-0000000101 keyspace -80 rdonly db-006:15302 db-006:17201 []
cell1-0000000102 keyspace -80 replica db-004:15302 db-004:17201 []
cell1-0000000200 keyspace 80- master db-005:15302 db-005:17201 []
cell1-0000000201 keyspace 80- rdonly db-007:15302 db-007:17201 []
cell1-0000000202 keyspace 80- replica db-008:15302 db-008:17201 []
cell1-0000000300 lookup 0 master db-002:15300 db-002:17300 []
cell1-0000000301 lookup 0 replica db-002:15301 db-002:17301 []
cell1-0000000302 lookup 0 replica db-002:15302 db-002:17302 []
cell1-0000000303 lookup 0 replica db-002:15303 db-002:17303 []
cell1-0000000304 lookup 0 replica db-002:15304 db-002:17304 []
cell1-0000002997 keyspace 0 rdonly db-997:15201 db-997:3306 []
cell1-0000002998 keyspace 0 replica db-998:15201 db-998:3306 []
cell1-0000002999 keyspace 0 replica db-999:15201 db-999:3306 []
```

## logging of ip addresses

```
10.aaa.bbb.cc  --> db-002
10.eee.fff.g   --> dns server in /etc/resolve.conf
```

## checking that the tablets are reachable

```
$ for alias in $(vtctlclient -server :15999 ListAllTablets cell1 | awk '{ print $1 }'); do echo  "$alias: $(if vtctlclient -server :15999 Ping $alias; then echo OK; fi)"; done
cell1-0000000100: OK
cell1-0000000101: OK
cell1-0000000102: OK
cell1-0000000200: OK
cell1-0000000201: OK
cell1-0000000202: OK
cell1-0000000300: OK
cell1-0000000301: OK
cell1-0000000302: OK
cell1-0000000303: OK
cell1-0000000304: OK
cell1-0000002997: OK
cell1-0000002998: OK
cell1-0000002999: OK
```

## Anonymisation

The following have been anonymised as consistently as possible
* paths
* hostnames and ip addresses
* keyspace names

The log file will be attached separately.

Any thoughts on what I'm doing wrong would be most appreciated.

**Comment by sjmudd** [comment]
[splitclone.log](https://github.com/youtube/vitess/files/1501434/splitclone.log)

Uploaded log file showing failed `SplitClone` run

**Comment by tirsen** [comment]
This is a known issue in master. It's a regression from upgrading to gRPC 1.7.1. If you instead grab a build from `b9599f4a06dc831ab826e166b23eff0a27c7b97a` it works better. Unfortunately this version doesn't build because of an old ZK version. You have to bump it up in bootstrap.sh: `zk_ver=3.4.11`

**Comment by sjmudd** [comment]
hm. ok. I'll try and see if I can figure this out next week with Sougou. I'd prefer not to backout of the latest vitess codebase and work with an older version of grpc if that works. Let's see the best way forward next week then.

**Comment by sougou** [comment]
This is a different variation of #3401. So, let's keep this open because the fix will need to be done at a different place.

As for the grpc spam, it's normal and expected. You'll see those even if things are working fine. It's an unfortunate decision we had to make (enabling grpc logging), because the grpc API does not return underlying errors to the caller: https://github.com/grpc/grpc-go/issues/1633.

FTR, This was the actual failure:
E1124 09:34:12.602199   32851 vtworker.go:98] online clone() failed: failed to split table into chunks: Cannot determine MIN and MAX of the first primary key column. ExecuteFetchAsApp: rpc error: code = Unavailable desc = grpc: the connection is unavailable

**Comment by sjmudd** [comment]
I'm fine keeping this open and was able to determine the actual problem. I just haven't been able to determine where in the grpc code this is broken etc. Please let me know if I can help debug this further or any suggestions you have to make progress resolving this.

**Comment by sjmudd** [comment]
I tried bumping the grpc version up to 1.7.2 (and remove $VTROOT/dist/grpc`) to see if that would help but it doesn't. I get the same error.

**Comment by sougou** [comment]
@sjmudd Looking at the code here: https://github.com/youtube/vitess/blob/master/go/vt/worker/chunk.go#L95. I think all you need to do is set a higher value for `remote_actions_timeout`.

I was going to add retries here, but setting a higher timeout should essentially do the same thing because grpc should retry. The default value is 1min. Can you try increasing to something higher?

**Comment by sjmudd** [comment]
I don't understand that.

The failure happens immediately (within a second) so it never gets to 1 minute. My logging shows this quite clearly.  So I do not think that adjusting that setting is going to make a difference.

**Comment by sougou** [comment]
It looks like extensive work is going on in grpc for retries. See the proposal here: https://github.com/grpc/proposal/blob/master/A6-client-retries.md.

Until then, can you try this small patch? I think this will make grpc retry if a connection is not ready: https://github.com/sougou/vitess/tree/grpc.

**Comment by sougou** [comment]
Also, if it doesn't work for 1.7.1, can you try upgrading to the 1.8.0 release (along with this patch). They seem to have added some additional retry logic in this latest release.
