### ISSUE TITLE
If VM is restarted, zk-up.sh fails to start zookeeper

### ISSUE THREAD

**Issue by rushiagr** [youtube/vitess#362]
Paste: http://paste.openstack.org/show/163121/

After restarting the VM, I just sourced dev.env, and ran `./zk-up.sh`. Didn't work

**Comment by enisoc** [comment]
Can you see if there is anything useful in `$VTDATAROOT/tmp/zkctl_*.out`?

**Comment by rushiagr** [comment]
Sorry, I couldn't spend time on reproducing this bug. I think we can just say that if the VM is rebooted/services go down, since this is a development environment only, just rm -rf the $VTDATAROOT directory and start all over again..

**Comment by enisoc** [comment]
Ah so the thing is that zk-up.sh is not the way you would start it up if you are intending to maintain state between runs. That's why it only works if $VTDATAROOT is empty.

Inside zk-up.sh, you can see it runs "zkctl ... init". That's the part that will fail if the directory is not empty. To start up a zkd with an existing directory contents, you would do "zkctl ... start".

You could alternatively use "zkctld ..." instead, with neither "init" nor "start". It will figure out whether to init or start based on whether the directory exists. The difference is that zkctld will remain running, and terminating zkctld will also terminate the actual zkd it's watching.

**Comment by rushiagr** [comment]
@enisoc thanks for that detailed analysis. We can close this issue. Maybe we can just add something in the docs that if system reboots, consider your environment gone if you're just using the scripts, or dig deeper and understand stuff :) 

Maybe later we can make the zk-up.sh script more intelligent to recover from an accidental reboot of the system..
