### ISSUE TITLE
Building vitess from git source won't success if you have only 512MB memory.

### ISSUE THREAD

**Issue by netroby** [youtube/vitess#474]
Building vitess from git source won't success if you have only 512MB memory.
The gcc error log said: can not allocate memory,.

So , the question is : what is the minmal requirement if we want build and install vitess?

any more details about it?

1Ghz or higher cpu
1GB or 2GB memory 
30GB hard disk space
1Mbps or more network can access the internet?

**Comment by enisoc** [comment]
It's hard to set a real minimum, especially since the minimum will change as we add dependencies and as the compilers evolve. I would say a nice safe recommendation for building is 4GB RAM. If you don't want to go through the hassle of building Vitess, you can also use prebuilt Docker images:

https://registry.hub.docker.com/repos/vitess/

**Comment by netroby** [comment]
@enisoc the docker images may be added to vitess getting started guide document. it will help many newbie who want to taste vitess. save many times.

**Comment by enisoc** [comment]
Thanks for the suggestion!
